.releaserc.yml
Added the "main" branch to the semantic release config.
=> fix: add release branch to semantic release config

.releaserc.yml
corrected issue with release config
=> fix: corrected issue with release config

README.md, src/commands/edge/channels/invites/accept.ts, src/lib/endpoints/invites.ts
* Fixed name of argument to accept command.
* Fixed request that accepts the request.
=> fix: use correct request when accepting an invite

package.json
- Added config to make npm publish public.
- Added other npm build steps.
=> fix: configure npm for public access

package.json
Added oclif manifest file to release.
=> fix: include oclif manifest file

package.json
use dist dir for commands instead of src
=> fix: use dist dir for commands instead of src

src/commands/edge/channels/unassign.ts
* updated to use `listAssignedDrivers` function
* use drivers `get` function to get name
* also catch 404 from driver `get` to but instead of weeding out drivers, here we just give the driver the name `<deleted driver>` so the user can still clean it up and remove it
=> fix: list only assigned drivers for unassign

README.md, src/commands/edge/drivers/package.ts
=> feat: add support for building and uploading edge drivers separately

README.md, src/commands/edge/drivers/logcat.ts, src/lib/live-logging.ts, test/unit/commands/edge/drivers/logcat.test.ts, test/unit/lib/live-logging.test.ts
* warn user that no drivers are installed when using the `--all` option
=> feat: verify host on first request

src/lib/endpoints/hubs.ts
* removed extraneous left curly brace
* removed unnecessary `Accept` header
=> fix: corrected request for installed device

README.md, src/commands/edge/drivers/package.ts, src/lib/commands/drivers/package-util.ts, src/lib/file-util.ts, test/unit/commands/edge/drivers/package.test.ts, test/unit/file-util.test.ts, test/unit/lib/commands/drivers/package-utils.test.ts
* refactored some code out of command itself to aid in unit testing
* completed unit tests for the `edge:drivers:package` command and associated code
=> test: add unit tests for edge:drivers:package command

.github/workflows/cd.yml, .github/workflows/ci.yml
- don't run release job on forks
- add npm cache
=> build: update node versions

README.md, src/commands/edge/drivers.ts
Updated documentation for `edge:drivers` command to be more accurate and include examples.
=> docs: update edge:drivers docs

README.md, package-lock.json, package.json, src/commands/edge/channels.ts, src/commands/edge/channels/metainfo.ts, src/commands/edge/channels/update.ts, src/commands/edge/drivers.ts, src/lib/commands/channels-util.ts, src/lib/commands/drivers-util.ts, test/unit/commands/edge/channels.test.ts, test/unit/commands/edge/channels/metainfo.test.ts, test/unit/commands/edge/drivers.test.ts
* updated to most recent cli lib (includes minor change to calling `forAllOrganizations` function
* added unit tests for`channels:metainfo`, `channels` and `drivers` commands
* minor refactoring for unit testing
=> test: add unit tests for recently-updated commands; minor fixes

README.md, package-lock.json, package.json, src/commands/edge/drivers/logcat.ts, src/lib/edge-client.ts, src/lib/edge-command.ts, src/lib/live-logging.ts, test/unit/commands/edge/drivers/logcat.test.ts, test/unit/lib/live-logging.test.ts
- bump @oclif packages
depends on https://github.com/SmartThingsCommunity/smartthings-cli/pull/260
=> feat: pass CLI User-Agent into client requests

README.md, src/commands/edge/drivers/logcat.ts
This should resolve a number of issues with terminal scrolling/selection behavior while logs are streaming.
=> fix(logcat): stop spinner on connection

README.md, package-lock.json, package.json, src/commands/edge/channels/invites/create.ts, src/commands/edge/drivers/package.ts, src/lib/edge-command.ts, test/unit/commands/edge/drivers/install.test.ts, test/unit/file-util.test.ts
* updated plugin to use changes to CLI config in mail CLI repo
* built with Node 16 as with the CLI which updated package-lock.json
See the [corresponding pull request](https://github.com/SmartThingsCommunity/smartthings-cli/pull/268) in the CLI for directions on how to test this.
=> refactor: update to refactored CLI config

.github/workflows/create-jira-issue.yaml, .github/workflows/stale.yaml
Added github actions for closing stale issues and creating JIRA issues.
These files are copied from the core SDK with the only change being that I added the "edge" component to the JIRA issue creation.
=> ci: add actions for closing stale issues and creating JIRA issues

src/lib/commands/drivers/package-util.ts, src/lib/file-util.ts, test/unit/file-util.test.ts, test/unit/lib/commands/drivers/package-util.test.ts
=> fix: strict type checking in YAML files

README.md, package-lock.json, package.json, src/commands/edge/drivers/logcat.ts
=> refactor: import colors from lib

README.md, jest.config.js, package-lock.json, package.json, src/lib/edge-command.ts, src/lib/live-logging.ts, test/unit/jest.setup.ts
=> feat: replace LogManager with log4js-api

README.md, src/commands/edge/drivers/package.ts, src/lib/commands/drivers/package-util.ts, src/lib/file-util.ts, test/unit/commands/edge/drivers/package.test.ts, test/unit/file-util.test.ts, test/unit/lib/commands/drivers/package-util.test.ts
* updated processing of files in source directory to be more deliberate about handling symbolic links
* don't allow links to directories
* log an error for a broken link
* updated some functions and the tests involving them to use promises
=> fix: log errors when symlinks point to directories or are broken

.github/workflows/stale.yaml
=> ci: set stale reason to not_planned

.eslintrc.js, test/unit/commands/edge/drivers/logcat.test.ts, test/unit/lib/commands/channels-util.test.ts, test/unit/lib/live-logging.test.ts
Align linting rules with the CLI.
See also https://github.com/SmartThingsCommunity/smartthings-cli/pull/364.
=> build: align linting rules with CLI

.eslintrc.js, README.md, package-lock.json, src/commands/edge/drivers/logcat.ts, test/unit/commands/edge/drivers/logcat.test.ts
Enable log filtering by severity level
=> feat: enable log filtering by severity level

README.md, jest.config.js, src/commands/edge/drivers/logcat.ts, src/lib/commands/drivers/logcat-util.ts, test/unit/commands/edge/drivers/logcat.test.ts, tsconfig.json
- resolve the breaking fix related to https://github.com/oclif/core/issues/453
=> fix(logcat): await SSE messages correctly

README.md, package-lock.json, package.json, src/commands/edge/drivers/logcat.ts, src/lib/live-logging.ts, test/unit/commands/edge/drivers/logcat.test.ts
=> fix(logcat): parse event before accessing log level

README.md, package-lock.json, package.json, src/commands/edge/channels.ts, src/commands/edge/channels/drivers.ts, src/commands/edge/channels/enrollments.ts, src/commands/edge/channels/invites.ts, src/commands/edge/channels/metainfo.ts, src/commands/edge/channels/unassign.ts, src/commands/edge/drivers.ts, src/commands/edge/drivers/default.ts, src/commands/edge/drivers/install.ts, src/commands/edge/drivers/installed.ts, src/commands/edge/drivers/logcat.ts, src/lib/commands/channels-util.ts, src/lib/commands/drivers-util.ts, test/unit/commands/edge/channels.test.ts, test/unit/commands/edge/channels/metainfo.test.ts, test/unit/commands/edge/drivers.test.ts, test/unit/commands/edge/drivers/installed.test.ts
* updated libraries to match CLI
* core SDK
* inquirier
* cli-lib and cli-testlib
* updated code for updated cli-lib
=> fix: update libraries to match CLI

src/commands/edge/drivers/installed.ts
Fixed incorrect field name used in display output.
=> fix: correct name of vendorSupportInformation field

src/commands/edge/drivers/installed.ts, test/unit/commands/edge/drivers/installed.test.ts
Fixed `primaryKeyId` for installed driver.
=> fix: correct primary key id for installed driver

README.md, src/commands/edge/channels.ts, src/commands/edge/channels/assign.ts, src/commands/edge/channels/enroll.ts, src/commands/edge/channels/invites.ts, src/commands/edge/channels/invites/create.ts, src/commands/edge/channels/invites/delete.ts, src/commands/edge/channels/metainfo.ts, src/commands/edge/channels/unassign.ts, src/commands/edge/channels/unenroll.ts, src/commands/edge/drivers/install.ts, src/commands/edge/drivers/installed.ts, src/commands/edge/drivers/package.ts, src/commands/edge/drivers/switch.ts, src/commands/edge/drivers/uninstall.ts
Added `helpValue` for flags that need UUIDs.
=> docs: include helpValue for flags that need UUIDs
